name: 🎵 Spotify Now Playing

on:
  schedule:
    # Runs every 15 minutes (reduced frequency to avoid rate limits)
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-spotify:
    name: Update Spotify Now Playing
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        
      - name: 🎵 Update Spotify Status
        uses: novatorem/novatorem@master
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_SECRET_ID: ${{ secrets.SPOTIFY_SECRET_ID }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 📝 Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Spotify Bot"
          
          if git diff --quiet; then
            echo "🎵 No Spotify updates to commit"
          else
            git add README.md
            git commit -m "🎵 Updated Spotify status - $(date +'%Y-%m-%d %H:%M UTC')" || echo "No changes to commit"
            git push || echo "Push completed"
            echo "✅ Spotify status updated successfully"
          fi
